version: '3.8'

services:
  website:
    build:
      context: .
      dockerfile: Dockerfile.dev
    container_name: ssd3900_github_pages_cicd
    ports:
      - '5173:5173'
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
    healthcheck:
      test: ['CMD', 'wget', '-qO-', 'http://localhost:5173']
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s
