# This is a template for your GitHub Actions workflow file
# You should modify this and place it in your repository at .github/workflows/deploy.yml

name: Deploy to GitHub Pages

# Controls when the workflow will run
on:
  # Triggers the workflow on push events but only for the main branch
  push:
    branches: [main]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# Required permissions for GitHub Pages deployment
permissions:
  contents: read
  pages: write
  id-token: write

# Allow only one concurrent deployment
concurrency:
  group: 'pages'
  cancel-in-progress: true

jobs:
  # Build job
  # - Responsible for compiling the application (e.g., running npm run build)
  #     and preparing the files needed for deployment.
  # - Needed to build the artifacts (./dist folder) and upload them
  #     to pass them to the deploy job
  build:
    runs-on: ubuntu-latest
    steps:
      # Clones the repository's code into the runner's workspace
      #     - Without this step, the runner (the virtual machine
      #         executing the workflow) would not have access to the repository's code
      # After this step runs, the repository's files will be available
      #     - in the runner's workspace, typically at
      #         /home/runner/work/<repository-name>/<repository-name>

      - name: Checkout repository
        uses: actions/checkout@v4

      # Setup your package manager (choose one of npm, yarn, or pnpm)

      # For npm:
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Build application
        run: npm run build

      # Upload artifact for deployment job
      # Zips the specified directory and uploads it as an artifact.
      - name: Upload Pages artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./dist

  # Deployment job
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    needs: build
    runs-on: ubuntu-latest
    steps:
      # Automates the deployment process to GitHub Pages

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4

      - name: Print Page URL
        run: echo 'GitHub Pages URL:' ${{ steps.deployment.outputs.page_url }}
